apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  namespace: "litmus"
  name: yeet-amf
spec:
  appinfo:
    appns: open5gs
    applabel: nf=amf
    appkind: deployment
  engineState: active
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: CHAOS_INTERVAL
              value: "10"
            - name: FORCE
              value: "true"
